import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import axios from "axios";
import types from "../types";

// base url of the api for managing car reservations
const url = "http://localhost:3000/reservations";

export const reserveCar = createAsyncThunk(types.RESERVE_CAR, async (car) => {
  const response = await axios.post(url, car);
  if (response.status === 200 && response.statusText === "OK") {
    return response.data;
  }
  return null;
});

export const fetchAllReservations = createAsyncThunk(
  types.FETCH_RESERVATIONS,
  async (_, { getState }) => {
    // eslint-disable-next-line
    const user = getState().user.user;
    // eslint-disable-next-line
    try {
      const response = await axios.get(url, {
        params: {
          user_id: user.id,
        },
      });

      return response.data;
    } catch (error) {
      // Manejar errores aquí si es necesario
      throw error;
    }
  }
);

// initial state for the redux slice
const initialState = {
  reservations: [],
  error: null,
  status: "idle",
};

const reservationsSlice = createSlice({
  name: "reservations",
  initialState,
  reducers: {
    reservations(state, action) {
      state.reservations = action.payload;
    },
  },
  // actions generated by fetchingallreservations
  extraReducers: (builder) => {
    builder
      .addCase(fetchAllReservations.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchAllReservations.fulfilled, (state, action) => {
        state.status = "succeeded";
        state.reservations = action.payload;
      })
      .addCase(fetchAllReservations.rejected, (state, action) => {
        state.status = "rejected";
        state.error = action.error.message;
      });
  },
});

export const { reservations } = reservationsSlice.actions;
export default reservationsSlice.reducer;
